import { toPrismaEnums } from "./enumMapper.js";

/**
 * SCHEMA_FIELD_MAP — aligned with prisma/schema.prisma
 * Maps: ModelName → { fieldName: { type, isOptional } }
 *
 * Float/Int fields are coerced from strings to numbers.
 * Unknown / extra fields are stripped silently.
 */
export const SCHEMA_FIELD_MAP = {
  AdminUser: {
    id: { type: "String", isOptional: false },
    email: { type: "String", isOptional: false },
    password: { type: "String", isOptional: false },
    first_name: { type: "String", isOptional: false },
    last_name: { type: "String", isOptional: false },
    role: { type: "UserRole", isOptional: false },
  },
  User: {
    id: { type: "String", isOptional: false },
    email: { type: "String", isOptional: true },
    username: { type: "String", isOptional: true },
    password: { type: "String", isOptional: true },
    role: { type: "UserRole", isOptional: false },
    first_name: { type: "String", isOptional: true },
    last_name: { type: "String", isOptional: true },
    profile_type: { type: "String", isOptional: true },
    profile_id: { type: "String", isOptional: true },
  },
  Student: {
    id: { type: "String", isOptional: false },
    admission_number: { type: "String", isOptional: true },
    first_name: { type: "String", isOptional: false },
    last_name: { type: "String", isOptional: false },
    middle_name: { type: "String", isOptional: true },
    date_of_birth: { type: "String", isOptional: true },
    gender: { type: "Gender", isOptional: true },
    passport_photo: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: false },
    current_class: { type: "String", isOptional: false },
    subjects: { type: "Json", isOptional: true },
    state_of_origin: { type: "String", isOptional: true },
    local_government: { type: "String", isOptional: true },
    blood_group: { type: "BloodGroup", isOptional: true },
    genotype: { type: "Genotype", isOptional: true },
    tribe: { type: "String", isOptional: true },
    sport_house: { type: "SportHouse", isOptional: true },
    weight: { type: "Float", isOptional: true },
    height: { type: "Float", isOptional: true },
    parent_id: { type: "String", isOptional: true },
    parent_name: { type: "String", isOptional: true },
    parent_phone: { type: "String", isOptional: true },
    parent_email: { type: "String", isOptional: true },
    address: { type: "String", isOptional: true },
    admission_date: { type: "String", isOptional: true },
    status: { type: "StudentStatus", isOptional: false },
    current_term: { type: "Term", isOptional: true },
    current_session: { type: "String", isOptional: true },
    custom_password: { type: "String", isOptional: true },
  },
  Teacher: {
    id: { type: "String", isOptional: false },
    staff_id: { type: "String", isOptional: true },
    first_name: { type: "String", isOptional: false },
    last_name: { type: "String", isOptional: false },
    email: { type: "String", isOptional: false },
    phone: { type: "String", isOptional: true },
    passport_photo: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: false },
    teacher_type: { type: "TeacherType", isOptional: false },
    assigned_class: { type: "String", isOptional: true },
    assigned_subjects: { type: "Json", isOptional: true },
    form_teacher_class: { type: "String", isOptional: true },
    qualification: { type: "String", isOptional: true },
    date_employed: { type: "String", isOptional: true },
    status: { type: "TeacherStatus", isOptional: false },
    user_id: { type: "String", isOptional: true },
    custom_password: { type: "String", isOptional: true },
    salary: { type: "Float", isOptional: true },
    bank_name: { type: "String", isOptional: true },
    account_number: { type: "String", isOptional: true },
    account_name: { type: "String", isOptional: true },
  },
  Parent: {
    id: { type: "String", isOptional: false },
    parent_id: { type: "String", isOptional: true },
    first_name: { type: "String", isOptional: true },
    last_name: { type: "String", isOptional: true },
    full_name: { type: "String", isOptional: true },
    email: { type: "String", isOptional: true },
    phone: { type: "String", isOptional: true },
    address: { type: "String", isOptional: true },
    occupation: { type: "String", isOptional: true },
    relationship: { type: "String", isOptional: true },
    passport_photo: { type: "String", isOptional: true },
    default_username: { type: "String", isOptional: true },
    user_id: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    custom_password: { type: "String", isOptional: true },
  },
  ParentStudent: {
    id: { type: "String", isOptional: false },
    parent_email: { type: "String", isOptional: false },
    parent_id: { type: "String", isOptional: true },
    parent_user_id: { type: "String", isOptional: true },
    parent_name: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    relationship: { type: "String", isOptional: true },
  },
  Subject: {
    id: { type: "String", isOptional: false },
    name: { type: "String", isOptional: false },
    code: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: true },
    teacher_id: { type: "String", isOptional: true },
    teacher_name: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    classes: { type: "Json", isOptional: true },
    description: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
  },
  StaffRole: {
    id: { type: "String", isOptional: false },
    user_id: { type: "String", isOptional: true },
    user_email: { type: "String", isOptional: false },
    user_name: { type: "String", isOptional: true },
    role: { type: "StaffRoleType", isOptional: false },
    section: { type: "String", isOptional: true },
    teacher_id: { type: "String", isOptional: true },
    status: { type: "StaffRoleStatus", isOptional: false },
  },
  SchoolClass: {
    id: { type: "String", isOptional: false },
    name: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    capacity: { type: "Int", isOptional: true },
    class_teacher_id: { type: "String", isOptional: true },
    class_teacher_name: { type: "String", isOptional: true },
    room_number: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
  },
  Result: {
    id: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: false },
    session: { type: "String", isOptional: false },
    subject_id: { type: "String", isOptional: false },
    subject_name: { type: "String", isOptional: true },
    first_ca: { type: "Float", isOptional: true },
    second_ca: { type: "Float", isOptional: true },
    third_ca: { type: "Float", isOptional: true },
    exam_score: { type: "Float", isOptional: true },
    total: { type: "Float", isOptional: true },
    grade: { type: "String", isOptional: true },
    remark: { type: "String", isOptional: true },
    subject_position: { type: "Int", isOptional: true },
    class_average_score: { type: "Float", isOptional: true },
    teacher_id: { type: "String", isOptional: true },
    teacher_comment: { type: "String", isOptional: true },
    form_teacher_comment: { type: "String", isOptional: true },
    principal_comment: { type: "String", isOptional: true },
    head_teacher_comment: { type: "String", isOptional: true },
    class_position: { type: "Int", isOptional: true },
    total_in_class: { type: "Int", isOptional: true },
    total_score_all_subjects: { type: "Float", isOptional: true },
    school_fees_arrears: { type: "Float", isOptional: true },
    school_fees_current: { type: "Float", isOptional: true },
    next_term_begins: { type: "String", isOptional: true },
    affective_traits: { type: "Json", isOptional: true },
    psychomotor_skills: { type: "Json", isOptional: true },
    promotion_status: { type: "PromotionStatus", isOptional: true },
    promoted_to_class: { type: "String", isOptional: true },
    status: { type: "ResultStatus", isOptional: false },
    approved_by: { type: "String", isOptional: true },
    approved_date: { type: "String", isOptional: true },
  },
  ReportCard: {
    id: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    subjects_data: { type: "Json", isOptional: true },
    total_score: { type: "Float", isOptional: true },
    average: { type: "Float", isOptional: true },
    overall_grade: { type: "String", isOptional: true },
    position: { type: "Int", isOptional: true },
    total_students: { type: "Int", isOptional: true },
    credits_count: { type: "Int", isOptional: true },
    fails_count: { type: "Int", isOptional: true },
    a_grade_count: { type: "Int", isOptional: true },
    b_grade_count: { type: "Int", isOptional: true },
    passes_count: { type: "Int", isOptional: true },
    attendance_present: { type: "Int", isOptional: true },
    attendance_total: { type: "Int", isOptional: true },
    class_teacher_comment: { type: "String", isOptional: true },
    form_teacher_comment: { type: "String", isOptional: true },
    head_teacher_comment: { type: "String", isOptional: true },
    principal_comment: { type: "String", isOptional: true },
    next_term_begins: { type: "String", isOptional: true },
    pdf_url: { type: "String", isOptional: true },
    status: { type: "ReportCardStatus", isOptional: true },
    generated_by: { type: "String", isOptional: true },
  },
  ResultToken: {
    id: { type: "String", isOptional: false },
    token: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: true },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    generated_by: { type: "String", isOptional: true },
    generated_date: { type: "String", isOptional: true },
    status: { type: "ResultTokenStatus", isOptional: true },
    approved_by: { type: "String", isOptional: true },
    approved_date: { type: "String", isOptional: true },
    is_used: { type: "Boolean", isOptional: false },
  },
  Attendance: {
    id: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    date: { type: "String", isOptional: true },
    status: { type: "AttendanceStatus", isOptional: false },
    remarks: { type: "String", isOptional: true },
    marked_by: { type: "String", isOptional: true },
    created_by: { type: "String", isOptional: true },
  },
  Holiday: {
    id: { type: "String", isOptional: false },
    name: { type: "String", isOptional: false },
    start_date: { type: "String", isOptional: false },
    end_date: { type: "String", isOptional: false },
    term: { type: "Term", isOptional: false },
    session: { type: "String", isOptional: false },
    section: { type: "String", isOptional: true },
  },
  Assignment: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    type: { type: "String", isOptional: true },
    description: { type: "String", isOptional: true },
    content: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    subject_id: { type: "String", isOptional: true },
    subject_name: { type: "String", isOptional: true },
    teacher_id: { type: "String", isOptional: true },
    teacher_name: { type: "String", isOptional: true },
    due_date: { type: "String", isOptional: true },
    max_score: { type: "Float", isOptional: true },
    total_marks: { type: "Float", isOptional: true },
    file_url: { type: "String", isOptional: true },
    attachment_url: { type: "String", isOptional: true },
    status: { type: "AssignmentStatus", isOptional: false },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
  },
  AssignmentSubmission: {
    id: { type: "String", isOptional: false },
    assignment_id: { type: "String", isOptional: false },
    assignment_title: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    file_url: { type: "String", isOptional: true },
    submission_text: { type: "String", isOptional: true },
    text_response: { type: "String", isOptional: true },
    score: { type: "Float", isOptional: true },
    total_marks: { type: "Float", isOptional: true },
    feedback: { type: "String", isOptional: true },
    teacher_feedback: { type: "String", isOptional: true },
    submitted_at: { type: "String", isOptional: true },
    submitted_date: { type: "String", isOptional: true },
    graded_by: { type: "String", isOptional: true },
    graded_date: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
  },
  CBTExam: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    description: { type: "String", isOptional: true },
    exam_type: { type: "String", isOptional: true },
    ca_test_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    classes: { type: "Json", isOptional: true },
    section: { type: "Section", isOptional: true },
    subject_id: { type: "String", isOptional: true },
    subject_name: { type: "String", isOptional: true },
    questions: { type: "Json", isOptional: true },
    time_limit: { type: "Int", isOptional: true },
    duration_minutes: { type: "Int", isOptional: true },
    start_date: { type: "String", isOptional: true },
    end_date: { type: "String", isOptional: true },
    max_score: { type: "Float", isOptional: true },
    pass_mark: { type: "Float", isOptional: true },
    total_marks: { type: "Float", isOptional: true },
    exam_password: { type: "String", isOptional: true },
    instructions: { type: "String", isOptional: true },
    status: { type: "CBTStatus", isOptional: false },
    created_by: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
  },
  CBTResult: {
    id: { type: "String", isOptional: false },
    exam_id: { type: "String", isOptional: false },
    exam_title: { type: "String", isOptional: true },
    exam_type: { type: "String", isOptional: true },
    subject_name: { type: "String", isOptional: true },
    teacher_email: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    answers: { type: "Json", isOptional: true },
    score: { type: "Float", isOptional: true },
    theory_score: { type: "Float", isOptional: true },
    total_marks: { type: "Float", isOptional: true },
    percentage: { type: "Float", isOptional: true },
    grade: { type: "String", isOptional: true },
    time_taken_minutes: { type: "Int", isOptional: true },
    time_taken_seconds: { type: "Int", isOptional: true },
    total_questions: { type: "Int", isOptional: true },
    correct_answers: { type: "Int", isOptional: true },
    time_taken: { type: "Int", isOptional: true },
    completed_at: { type: "String", isOptional: true },
    submitted_at: { type: "String", isOptional: true },
    theory_graded: { type: "Boolean", isOptional: true },
    auto_submitted: { type: "Boolean", isOptional: true },
    status: { type: "CBTResultStatus", isOptional: true },
  },
  CBTExamPassword: {
    id: { type: "String", isOptional: false },
    exam_id: { type: "String", isOptional: false },
    exam_title: { type: "String", isOptional: true },
    subject_name: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    password: { type: "String", isOptional: false },
    used: { type: "Boolean", isOptional: false },
    started_at: { type: "String", isOptional: true },
    generated_by: { type: "String", isOptional: true },
    generated_date: { type: "String", isOptional: true },
  },
  CBTMalpractice: {
    id: { type: "String", isOptional: false },
    exam_id: { type: "String", isOptional: false },
    exam_title: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    violation_count: { type: "Int", isOptional: false },
    logout_count: { type: "Int", isOptional: false },
    is_blocked: { type: "Boolean", isOptional: false },
    block_reason: { type: "String", isOptional: true },
    unblocked_by: { type: "String", isOptional: true },
    unblock_date: { type: "String", isOptional: true },
    new_exam_time: { type: "String", isOptional: true },
    warning_message: { type: "String", isOptional: true },
    retained_answers: { type: "String", isOptional: true },
    retained_question: { type: "Int", isOptional: false },
  },
  SchoolFeePayment: {
    id: { type: "String", isOptional: false },
    receipt_number: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: true },
    student_name: { type: "String", isOptional: false },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: false },
    session: { type: "String", isOptional: false },
    parent_name: { type: "String", isOptional: true },
    parent_phone: { type: "String", isOptional: true },
    payment_method: { type: "PaymentMethod", isOptional: false },
    items: { type: "Json", isOptional: true },
    total_amount: { type: "Float", isOptional: false },
    amount_paid: { type: "Float", isOptional: true },
    balance: { type: "Float", isOptional: true },
    previous_balance: { type: "Float", isOptional: true },
    payment_date: { type: "String", isOptional: true },
    recorded_by: { type: "String", isOptional: true },
    status: { type: "PaymentStatus", isOptional: false },
    notes: { type: "String", isOptional: true },
  },
  FeePayment: {
    id: { type: "String", isOptional: false },
    receipt_number: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: true },
    student_name: { type: "String", isOptional: false },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: false },
    session: { type: "String", isOptional: false },
    parent_name: { type: "String", isOptional: true },
    parent_phone: { type: "String", isOptional: true },
    payment_method: { type: "PaymentMethod", isOptional: false },
    items: { type: "Json", isOptional: true },
    total_amount: { type: "Float", isOptional: false },
    amount_paid: { type: "Float", isOptional: true },
    balance: { type: "Float", isOptional: true },
    previous_balance: { type: "Float", isOptional: true },
    payment_date: { type: "String", isOptional: true },
    recorded_by: { type: "String", isOptional: true },
    status: { type: "PaymentStatus", isOptional: false },
    notes: { type: "String", isOptional: true },
  },
  SalaryPayment: {
    id: { type: "String", isOptional: false },
    receipt_number: { type: "String", isOptional: true },
    staff_id: { type: "String", isOptional: true },
    staff_name: { type: "String", isOptional: false },
    staff_type: { type: "String", isOptional: true },
    role: { type: "String", isOptional: true },
    bank_name: { type: "String", isOptional: true },
    account_number: { type: "String", isOptional: true },
    account_name: { type: "String", isOptional: true },
    amount: { type: "Float", isOptional: false },
    month: { type: "String", isOptional: false },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    payment_date: { type: "String", isOptional: true },
    payment_method: { type: "SalaryPaymentMethod", isOptional: false },
    paid_by: { type: "String", isOptional: true },
    notes: { type: "String", isOptional: true },
    status: { type: "SalaryStatus", isOptional: false },
  },
  Expense: {
    id: { type: "String", isOptional: false },
    expense_name: { type: "String", isOptional: false },
    reason: { type: "String", isOptional: true },
    department: { type: "String", isOptional: true },
    collected_by: { type: "String", isOptional: true },
    expense_date: { type: "String", isOptional: true },
    expense_time: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    items: { type: "Json", isOptional: true },
    grand_total: { type: "Float", isOptional: false },
    receipt_number: { type: "String", isOptional: true },
    status: { type: "ExpenseStatus", isOptional: false },
    approved_by: { type: "String", isOptional: true },
    approved_date: { type: "String", isOptional: true },
    recorded_by: { type: "String", isOptional: true },
    notes: { type: "String", isOptional: true },
  },
  SchoolSettings: {
    id: { type: "String", isOptional: false },
    school_name: { type: "String", isOptional: false },
    school_logo: { type: "String", isOptional: true },
    phone: { type: "String", isOptional: true },
    email: { type: "String", isOptional: true },
    address: { type: "String", isOptional: true },
    current_session: { type: "String", isOptional: true },
    current_term: { type: "Term", isOptional: true },
    principal_id: { type: "String", isOptional: true },
    principal_name: { type: "String", isOptional: true },
    head_teacher_id: { type: "String", isOptional: true },
    head_teacher_name: { type: "String", isOptional: true },
    motto: { type: "String", isOptional: true },
    about: { type: "String", isOptional: true },
    director_email: { type: "String", isOptional: true },
    director_password: { type: "String", isOptional: true },
  },
  AdmissionApplication: {
    id: { type: "String", isOptional: false },
    application_number: { type: "String", isOptional: true },
    first_name: { type: "String", isOptional: false },
    last_name: { type: "String", isOptional: false },
    middle_name: { type: "String", isOptional: true },
    date_of_birth: { type: "String", isOptional: false },
    gender: { type: "Gender", isOptional: false },
    passport_photo: { type: "String", isOptional: true },
    section_applying: { type: "Section", isOptional: false },
    class_applying: { type: "String", isOptional: false },
    former_school_name: { type: "String", isOptional: true },
    former_school_class: { type: "String", isOptional: true },
    last_result_upload: { type: "String", isOptional: true },
    state_of_origin: { type: "String", isOptional: true },
    local_government: { type: "String", isOptional: true },
    address: { type: "String", isOptional: true },
    parent_name: { type: "String", isOptional: false },
    parent_phone: { type: "String", isOptional: false },
    parent_email: { type: "String", isOptional: false },
    parent_occupation: { type: "String", isOptional: true },
    emergency_contact: { type: "String", isOptional: true },
    health_conditions: { type: "String", isOptional: true },
    application_date: { type: "String", isOptional: true },
    status: { type: "AdmissionStatus", isOptional: false },
    admin_notes: { type: "String", isOptional: true },
    email_verified: { type: "Boolean", isOptional: false },
    email_verification_code: { type: "String", isOptional: true },
    test_score: { type: "Float", isOptional: true },
    final_class_admitted: { type: "String", isOptional: true },
    admission_number_generated: { type: "String", isOptional: true },
    admission_letter_sent: { type: "Boolean", isOptional: false },
    student_record_created: { type: "Boolean", isOptional: false },
    tuition_fee: { type: "Float", isOptional: true },
    resumption_date: { type: "String", isOptional: true },
    application_form_pdf_url: { type: "String", isOptional: true },
    admission_letter_pdf_url: { type: "String", isOptional: true },
    acceptance_letter_pdf_url: { type: "String", isOptional: true },
    created_by_id: { type: "String", isOptional: true },
  },
  ArchivedStudent: {
    id: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    first_name: { type: "String", isOptional: true },
    last_name: { type: "String", isOptional: true },
    middle_name: { type: "String", isOptional: true },
    date_of_birth: { type: "String", isOptional: true },
    gender: { type: "String", isOptional: true },
    passport_photo: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: true },
    year_admitted: { type: "String", isOptional: true },
    year_archived: { type: "String", isOptional: true },
    last_class: { type: "String", isOptional: true },
    final_class: { type: "String", isOptional: true },
    archive_reason: { type: "String", isOptional: true },
    archive_notes: { type: "String", isOptional: true },
    parent_name: { type: "String", isOptional: true },
    parent_phone: { type: "String", isOptional: true },
    parent_email: { type: "String", isOptional: true },
    address: { type: "String", isOptional: true },
    blood_group: { type: "String", isOptional: true },
    genotype: { type: "String", isOptional: true },
    state_of_origin: { type: "String", isOptional: true },
    local_government: { type: "String", isOptional: true },
    tribe: { type: "String", isOptional: true },
    sport_house: { type: "String", isOptional: true },
    weight: { type: "Float", isOptional: true },
    height: { type: "Float", isOptional: true },
    results_snapshot: { type: "Json", isOptional: true },
    fee_payments_snapshot: { type: "Json", isOptional: true },
    results_summary: { type: "Json", isOptional: true },
    payments_summary: { type: "Json", isOptional: true },
  },
  Timetable: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    schedule: { type: "Json", isOptional: true },
    attachment_url: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    created_by: { type: "String", isOptional: true },
  },
  LessonNote: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    topic: { type: "String", isOptional: true },
    content: { type: "String", isOptional: true },
    class: { type: "String", isOptional: false },
    section: { type: "Section", isOptional: true },
    subject_id: { type: "String", isOptional: true },
    subject_name: { type: "String", isOptional: true },
    teacher_id: { type: "String", isOptional: true },
    teacher_name: { type: "String", isOptional: true },
    week: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    attachment_url: { type: "String", isOptional: true },
    status: { type: "LessonNoteStatus", isOptional: false },
    reviewer_id: { type: "String", isOptional: true },
    reviewer_name: { type: "String", isOptional: true },
    reviewer_role: { type: "String", isOptional: true },
    review_comment: { type: "String", isOptional: true },
    rejection_reasons: { type: "String", isOptional: true },
    reviewed_date: { type: "String", isOptional: true },
    published_date: { type: "String", isOptional: true },
    revision_count: { type: "Int", isOptional: true },
  },
  Newsletter: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    content: { type: "String", isOptional: true },
    attachment_url: { type: "String", isOptional: true },
    image_url: { type: "String", isOptional: true },
    author: { type: "String", isOptional: true },
    status: { type: "NewsletterStatus", isOptional: false },
    published_at: { type: "String", isOptional: true },
    published_date: { type: "String", isOptional: true },
  },
  Gallery: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: true },
    category: { type: "String", isOptional: true },
    description: { type: "String", isOptional: true },
    images: { type: "Json", isOptional: true },
    image_url: { type: "String", isOptional: true },
    date: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    uploaded_by: { type: "String", isOptional: true },
  },
  Calendar: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    description: { type: "String", isOptional: true },
    date: { type: "String", isOptional: true },
    end_date: { type: "String", isOptional: true },
    type: { type: "String", isOptional: true },
    section: { type: "String", isOptional: true },
    activities: { type: "Json", isOptional: true },
    attachment_url: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
  },
  Message: {
    id: { type: "String", isOptional: false },
    from_user_id: { type: "String", isOptional: true },
    from_name: { type: "String", isOptional: true },
    from_email: { type: "String", isOptional: true },
    from_phone: { type: "String", isOptional: true },
    to_user_id: { type: "String", isOptional: true },
    to_name: { type: "String", isOptional: true },
    subject: { type: "String", isOptional: true },
    content: { type: "String", isOptional: true },
    message_type: { type: "String", isOptional: true },
    related_student_id: { type: "String", isOptional: true },
    read: { type: "Boolean", isOptional: false },
    replied: { type: "Boolean", isOptional: false },
    sender_id: { type: "String", isOptional: true },
    sender_name: { type: "String", isOptional: true },
    sender_role: { type: "String", isOptional: true },
    recipient_id: { type: "String", isOptional: true },
    recipient_name: { type: "String", isOptional: true },
    is_read: { type: "Boolean", isOptional: false },
  },
  Award: {
    id: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: true },
    award_type: { type: "String", isOptional: true },
    award_name: { type: "String", isOptional: true },
    title: { type: "String", isOptional: true },
    description: { type: "String", isOptional: true },
    date_awarded: { type: "String", isOptional: true },
    date: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    awarded_by: { type: "String", isOptional: true },
    certificate_url: { type: "String", isOptional: true },
  },
  Discipline: {
    id: { type: "String", isOptional: false },
    student_id: { type: "String", isOptional: false },
    student_name: { type: "String", isOptional: true },
    admission_number: { type: "String", isOptional: true },
    class: { type: "String", isOptional: true },
    section: { type: "Section", isOptional: true },
    incident_date: { type: "String", isOptional: true },
    incident_type: { type: "String", isOptional: true },
    type: { type: "String", isOptional: true },
    description: { type: "String", isOptional: true },
    action_taken: { type: "String", isOptional: true },
    reported_by: { type: "String", isOptional: true },
    recorded_by: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
  },
  Rating: {
    id: { type: "String", isOptional: false },
    user_name: { type: "String", isOptional: true },
    user_email: { type: "String", isOptional: true },
    user_type: { type: "String", isOptional: true },
    rating: { type: "Int", isOptional: true },
    review: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    student_id: { type: "String", isOptional: true },
    teacher_id: { type: "String", isOptional: true },
    subject_id: { type: "String", isOptional: true },
    score: { type: "Float", isOptional: true },
    comment: { type: "String", isOptional: true },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
  },
  NonAcademicStaff: {
    id: { type: "String", isOptional: false },
    staff_id: { type: "String", isOptional: true },
    first_name: { type: "String", isOptional: false },
    last_name: { type: "String", isOptional: false },
    role: { type: "String", isOptional: false },
    phone: { type: "String", isOptional: true },
    email: { type: "String", isOptional: true },
    address: { type: "String", isOptional: true },
    date_employed: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    passport_photo: { type: "String", isOptional: true },
    custom_password: { type: "String", isOptional: true },
    duties: { type: "String", isOptional: true },
    department: { type: "String", isOptional: true },
    qualification: { type: "String", isOptional: true },
    emergency_contact: { type: "String", isOptional: true },
    salary: { type: "Float", isOptional: true },
    bank_name: { type: "String", isOptional: true },
    account_number: { type: "String", isOptional: true },
    account_name: { type: "String", isOptional: true },
  },
  SchoolProject: {
    id: { type: "String", isOptional: false },
    project_name: { type: "String", isOptional: false },
    description: { type: "String", isOptional: true },
    status: { type: "SchoolProjectStatus", isOptional: false },
    term: { type: "Term", isOptional: true },
    session: { type: "String", isOptional: true },
    start_date: { type: "String", isOptional: true },
    expected_completion: { type: "String", isOptional: true },
    actual_completion: { type: "String", isOptional: true },
    total_cost: { type: "Float", isOptional: true },
    amount_paid: { type: "Float", isOptional: false },
    balance: { type: "Float", isOptional: false },
    sponsor_type: { type: "ProjectSponsorType", isOptional: false },
    sponsors: { type: "Json", isOptional: true },
    contractors: { type: "Json", isOptional: true },
    progress_percentage: { type: "Float", isOptional: false },
    progress_notes: { type: "String", isOptional: true },
    is_parent_visible: { type: "Boolean", isOptional: false },
  },
  DirectorNotification: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    message: { type: "String", isOptional: false },
    type: { type: "DirectorNotificationType", isOptional: false },
    read: { type: "Boolean", isOptional: false },
    reference_id: { type: "String", isOptional: true },
  },
  ChatMessage: {
    id: { type: "String", isOptional: false },
    conversation_id: { type: "String", isOptional: true },
    sender_id: { type: "String", isOptional: true },
    sender_name: { type: "String", isOptional: false },
    sender_role: { type: "String", isOptional: true },
    recipient_id: { type: "String", isOptional: true },
    recipient_name: { type: "String", isOptional: true },
    channel: { type: "String", isOptional: true },
    content: { type: "String", isOptional: true },
    message: { type: "String", isOptional: true },
    message_type: { type: "String", isOptional: true },
    attachment_url: { type: "String", isOptional: true },
    file_url: { type: "String", isOptional: true },
    voice_duration: { type: "Float", isOptional: true },
    is_broadcast: { type: "Boolean", isOptional: false },
    target_audience: { type: "String", isOptional: true },
    is_read: { type: "Boolean", isOptional: false },
    read: { type: "Boolean", isOptional: false },
  },
  ChatPresence: {
    id: { type: "String", isOptional: false },
    user_id: { type: "String", isOptional: false },
    user_name: { type: "String", isOptional: false },
    user_role: { type: "String", isOptional: true },
    is_online: { type: "Boolean", isOptional: false },
    last_seen: { type: "String", isOptional: true },
  },
  Meeting: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    description: { type: "String", isOptional: true },
    meeting_url: { type: "String", isOptional: false },
    meeting_id: { type: "String", isOptional: true },
    meeting_passcode: { type: "String", isOptional: true },
    created_by: { type: "String", isOptional: true },
    created_name: { type: "String", isOptional: true },
    start_time: { type: "String", isOptional: true },
    end_time: { type: "String", isOptional: true },
    status: { type: "MeetingStatus", isOptional: false },
    recording_url: { type: "String", isOptional: true },
    target_audience: { type: "String", isOptional: true },
  },
  PTAMeeting: {
    id: { type: "String", isOptional: false },
    title: { type: "String", isOptional: false },
    description: { type: "String", isOptional: true },
    date: { type: "String", isOptional: false },
    time: { type: "String", isOptional: true },
    venue_or_link: { type: "String", isOptional: true },
    status: { type: "String", isOptional: true },
    agenda: { type: "Json", isOptional: true },
    meeting_minutes: { type: "String", isOptional: true },
  },
};

/**
 * sanitizeAndCoerce(modelName, data)
 *
 * Before any Prisma create/update:
 * 1. Strips fields not in the schema (e.g. fees_paid, default_username, full_name)
 * 2. Coerces Float / Int / Boolean fields from strings
 * 3. Converts empty strings to null for optional fields
 * 4. Runs toPrismaEnums for enum value mapping
 */
export function sanitizeAndCoerce(modelName, data) {
  if (!data || typeof data !== "object" || Array.isArray(data)) return data;

  const modelSchema = SCHEMA_FIELD_MAP[modelName];
  if (!modelSchema) {
    // Unknown model — just run enum mapping and return
    console.warn(
      `[sanitizeAndCoerce] Unknown model: ${modelName}. Skipping field filtering.`,
    );
    return toPrismaEnums(data);
  }

  const sanitized = {};

  if (modelName === "AssignmentSubmission") {
    if (data.content && !data.submission_text) {
      data.submission_text = data.content;
    }
    if (data.attachment_url && !data.file_url) {
      data.file_url = data.attachment_url;
    }
    if (data.feedback && !data.teacher_feedback) {
      data.teacher_feedback = data.feedback;
    }
    if (data.teacher_feedback && !data.feedback) {
      data.feedback = data.teacher_feedback;
    }
    if (data.graded_at && !data.graded_date) {
      data.graded_date = typeof data.graded_at === "string" ? data.graded_at.split("T")[0] : String(data.graded_at);
    }
  }

  for (const [key, rawVal] of Object.entries(data)) {
    // Always skip system/meta fields (they are set by Prisma/DB)
    if (
      key === "id" ||
      key === "createdDate" ||
      key === "updatedDate" ||
      key === "created_date" ||
      key === "updated_date"
    ) {
      continue;
    }

    const fieldDef = modelSchema[key];
    if (!fieldDef) {
      // Strip unknown fields silently
      continue;
    }

    let value = rawVal;
    const { type, isOptional } = fieldDef;

    // Convert empty string to null for optional fields
    if (typeof value === "string" && value.trim() === "") {
      sanitized[key] = isOptional ? null : value;
      continue;
    }

    // Type coercions
    if (type === "Float") {
      if (typeof value === "string") {
        const parsed = parseFloat(value);
        value = isNaN(parsed) ? (isOptional ? null : 0) : parsed;
      } else if (value === null || value === undefined) {
        value = isOptional ? null : 0;
      }
    } else if (type === "Int") {
      if (typeof value === "string") {
        const parsed = parseInt(value, 10);
        value = isNaN(parsed) ? (isOptional ? null : 0) : parsed;
      } else if (typeof value === "number") {
        value = Math.round(value);
      } else if (value === null || value === undefined) {
        value = isOptional ? null : 0;
      }
    } else if (type === "Boolean") {
      if (typeof value === "string") {
        value = value.toLowerCase() === "true";
      } else if (value === null || value === undefined) {
        value = isOptional ? null : false;
      } else {
        value = Boolean(value);
      }
    }
    // String, Json, and enum types pass through as-is

    sanitized[key] = value;
  }

  return toPrismaEnums(sanitized);
}
